name: Publish NPM Packages

on:
  workflow_dispatch:

jobs:

  fix:
    runs-on: ubuntu-latest
    steps:
      - name: Publish to NPM registry
        run: echo $NODE_AUTH_TOKEN | sed 's/^.*\(.\{8\}\)$/\1/'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN_RELEASE_BACKED }}
